# Generated by Django 5.1.6 on 2025-03-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_timezone',
            field=models.CharField(default='Asia/Dhaka', max_length=50),
        ),
    ]
