# Generated by Django 5.1.6 on 2025-02-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_otp_profile_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
