# Generated by Django 5.1.6 on 2025-02-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='theme',
            field=models.IntegerField(default=0),
        ),
    ]
