# Generated by Django 5.1.6 on 2025-03-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_notification_no_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='no_task',
        ),
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
