# Generated by Django 5.1.6 on 2025-03-26 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_remove_notification_no_task_alter_notification_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irrigate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(help_text='Duration of irrigation in minutes')),
                ('command', models.BooleanField(default=False, help_text='On/Off command for irrigation')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the irrigation was actually performed')),
            ],
            options={
                'ordering': ['-action_time'],
            },
        ),
    ]
