# Generated by Django 5.1.6 on 2025-03-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0006_alter_irrigate_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
