# Generated by Django 5.1.6 on 2025-04-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0007_alter_notification_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinetemplate',
            name='taskCount',
            field=models.IntegerField(default=0),
        ),
    ]
