# Generated by Django 5.1.6 on 2025-03-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_archivedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictask',
            name='duration',
            field=models.IntegerField(default=20),
        ),
    ]
