# Generated by Django 5.1.6 on 2025-03-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_publictask_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictask',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.publictaskcategory'),
        ),
    ]
