# Generated by Django 5.1.6 on 2025-02-19 07:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskcategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('user', 'title', 'task_type')},
        ),
    ]
