# Generated by Django 5.1.6 on 2025-02-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_taskcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
