# Generated by Django 5.1.6 on 2025-02-19 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_taskcategory_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_duration',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notification_days',
            field=models.IntegerField(default=0),
        ),
    ]
