# Generated by Django 5.1.6 on 2025-02-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_task_task_duration_remove_task_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AddField(
            model_name='task',
            name='frequency_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_repetitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publictask',
            name='task_type',
            field=models.CharField(choices=[], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='notification_days',
            field=models.IntegerField(default=1),
        ),
    ]
