# Generated by Django 5.1.6 on 2025-02-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_task_frequency_remove_task_task_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publictask',
            name='task_duration',
        ),
        migrations.RemoveField(
            model_name='publictask',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='publictask',
            name='time',
        ),
        migrations.AddField(
            model_name='publictask',
            name='frequency_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publictask',
            name='is_repetitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publictask',
            name='notification_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='publictask',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.taskcategory'),
        ),
        migrations.AlterField(
            model_name='publictask',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
